/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZUNiV0RKeE1sYmF3TUZZdlI1aXk5UytrY002RklNa0E5TllISTlkaFRuTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidEdhMi8vUmptKytOcCtjQnlZTEkxZ2NMKzlRUEIvcXczZWorZDlNdjVUUT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJFQ3JOMTllSWRWb2prY3BUOVhUclVENU8yQW1LL2k4REE0OVEzRjVCUjFVPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJWTGVIQVBaY25zcDhPcmVaMVZZVTV4ckpkbldHaDNuSGhaQ3M4MFUreWdFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklKSmt5UkVzSExqdWVNdms0anJJbGZmd2srMXVYS0ZDdTRkTy9vTlp0VTg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik0zV3R4OGZQNWt5YXdBcDJFdFMrNjNUa0ltNStJRjhtTloxTmpRYkVqd0k9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS040UXhneHVnQlhjaXBta0toNGVrU2plNnlYc1ZBRUtLU05SRWNXemFuaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiejZsYzBIRmJ2Z2hKKzdMYjl5aEJ0dGRTRWRKcFZFNzBrcnNxTC9BaVRITT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InNGdS9xVm56MFVhcVNtMHBmd0ZiUlUvSWJXeHBMeFBFbzJVQTdnc2tlUkJ4ZVVjNDdLWTYydkZwZmFiMkxBZHQwaHhSaExFRnc0dllIWldQN0Q1UEJRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjI0LCJhZHZTZWNyZXRLZXkiOiJOUWFIaGZKTzJjczQ0RmRNalB5ZWVGL09BRisvZ2NxK3RoY1JFcy9KOGtzPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc1Nzk4ODgxNUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI5MjQyQkYwM0FENjU3QjUxMkJGOUQ4RTQzOEZFOTZDRiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzM0NDQxNzE2fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJJeEY1T1hCTVRIYTJDa3pYSUdiYTFBIiwicGhvbmVJZCI6IjI5ZDlmNGM0LWYyOTItNDVlZi05OWYwLTkxN2NlMzY4MWViMiIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJIRTIxWGFYV0NvVzBlUTRtcGU1cDhlUHFPZG89In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZncxSFVhV1RZQkZKeDMyRmczRHZwaE5vWGRNPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkNQSkNKWTI5IiwibWUiOnsiaWQiOiIyNTQ3NTc5ODg4MTU6ODlAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiS2lwcmljaCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTmFVeU9JQ0VMSDFoYnNHR0E0Z0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiRG5uQ1dLK2lhTDd0N0x0WmFSL0NVT2UvbjFob29mVFljL3VkazBTSVRDcz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiZmYzUVRadnNBUnJpc0xBVk54WGt4TFdzZm5DV1Q0U2pwbTVQV2J2b21MT1FtTVFNVXZncTVrMVhoWDlobGN4K2RsbU10UFh6UC81UmVpZmZWV0hCQlE9PSIsImRldmljZVNpZ25hdHVyZSI6IjBjSkVZWld1dkV4VE1FbGIwcWZzVUlSUEZUR0w1WEhSdFhiSWNXSThEbzRIU3dQcm5ySzdudnlBVVduZGtoSE5zajg0dmxubHlJVVpEQldQQ2lSS0J3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzU3OTg4ODE1Ojg5QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlE1NXdsaXZvbWkrN2V5N1dXa2Z3bERudjU5WWFLSDAySFA3blpORWlFd3IifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzQ0NDE2ODQsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBUGF5In0=';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254757988815";
const author = process.env.STICKER_AUTHOR || 'fortunatus';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '254757988815';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DREADED';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'false';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
autolike,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
